# Generated by Django 5.2.10 on 2026-01-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendance_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='absent_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='present_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='total_students',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
