# Generated by Django 5.2.10 on 2026-01-21 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendancesession_absent_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('date', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(default='Current Semester', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('course', 'exam_type', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+ (90-100)'), ('A', 'A (85-89)'), ('A-', 'A- (80-84)'), ('B+', 'B+ (75-79)'), ('B', 'B (70-74)'), ('B-', 'B- (65-69)'), ('C+', 'C+ (60-64)'), ('C', 'C (55-59)'), ('C-', 'C- (50-54)'), ('D', 'D (40-49)'), ('F', 'F (0-39)')], max_length=2, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='api.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
